const colleges = [
  {
    rank: 1,
    logo: "url/to/iitmadras-logo.png",
    name: "IIT Madras - Indian Institute of Technology",
    location: "Chennai, Tamil Nadu",
    approval: "AICTE Approved",
    course: {
      name: "B.Tech Artificial Intelligence",
      exam: "JEE-Advanced",
      cutoff: 419,
    },
    fees: 242000,
    placement: {
      average: 2148000,
      highest: 19800000,
    },
    userReviews: {
      rating: 4.3,
      totalReviews: 374,
      badge: "Best in Social Life",
    },
    nationalRank: 3,
    totalColleges: 275,
    rankingAgencies: ["The Week", "NIRF", "QS"],
  },
  {
    rank: 2,
    logo: "url/to/iitmadras-logo.png",
    name: "IIT Madras - Indian Institute of Technology",
    location: "Chennai, Tamil Nadu",
    approval: "AICTE Approved",
    course: {
      name: "B.Tech Artificial Intelligence",
      exam: "JEE-Advanced",
      cutoff: 419,
    },
    fees: 242000,
    placement: {
      average: 2148000,
      highest: 19800000,
    },
    userReviews: {
      rating: 4.3,
      totalReviews: 374,
      badge: "Best in Social Life",
    },
    nationalRank: 3,
    totalColleges: 275,
    rankingAgencies: ["The Week", "NIRF", "QS"],
  },
  {
    rank: 3,
    logo: "url/to/iitmadras-logo.png",
    name: "IIT Madras - Indian Institute of Technology",
    location: "Chennai, Tamil Nadu",
    approval: "AICTE Approved",
    course: {
      name: "B.Tech Artificial Intelligence",
      exam: "JEE-Advanced",
      cutoff: 419,
    },
    fees: 242000,
    placement: {
      average: 2148000,
      highest: 19800000,
    },
    userReviews: {
      rating: 4.3,
      totalReviews: 374,
      badge: "Best in Social Life",
    },
    nationalRank: 3,
    totalColleges: 275,
    rankingAgencies: ["The Week", "NIRF", "QS"],
  },
  {
    rank: 4,
    logo: "url/to/iitmadras-logo.png",
    name: "IIT Madras - Indian Institute of Technology",
    location: "Chennai, Tamil Nadu",
    approval: "AICTE Approved",
    course: {
      name: "B.Tech Artificial Intelligence",
      exam: "JEE-Advanced",
      cutoff: 419,
    },
    fees: 242000,
    placement: {
      average: 2148000,
      highest: 19800000,
    },
    userReviews: {
      rating: 4.3,
      totalReviews: 374,
      badge: "Best in Social Life",
    },
    nationalRank: 3,
    totalColleges: 275,
    rankingAgencies: ["The Week", "NIRF", "QS"],
  },
  {
    rank: 5,
    logo: "url/to/iitmadras-logo.png",
    name: "IIT Madras - Indian Institute of Technology",
    location: "Chennai, Tamil Nadu",
    approval: "AICTE Approved",
    course: {
      name: "B.Tech Artificial Intelligence",
      exam: "JEE-Advanced",
      cutoff: 419,
    },
    fees: 242000,
    placement: {
      average: 2148000,
      highest: 19800000,
    },
    userReviews: {
      rating: 4.3,
      totalReviews: 374,
      badge: "Best in Social Life",
    },
    nationalRank: 3,
    totalColleges: 275,
    rankingAgencies: ["The Week", "NIRF", "QS"],
  },
  {
    rank: 6,
    logo: "url/to/iitmadras-logo.png",
    name: "IIT Madras - Indian Institute of Technology",
    location: "Chennai, Tamil Nadu",
    approval: "AICTE Approved",
    course: {
      name: "B.Tech Artificial Intelligence",
      exam: "JEE-Advanced",
      cutoff: 419,
    },
    fees: 242000,
    placement: {
      average: 2148000,
      highest: 19800000,
    },
    userReviews: {
      rating: 4.3,
      totalReviews: 374,
      badge: "Best in Social Life",
    },
    nationalRank: 3,
    totalColleges: 275,
    rankingAgencies: ["The Week", "NIRF", "QS"],
  },
  {
    rank: 7,
    logo: "url/to/iitmadras-logo.png",
    name: "IIT Madras - Indian Institute of Technology",
    location: "Chennai, Tamil Nadu",
    approval: "AICTE Approved",
    course: {
      name: "B.Tech Artificial Intelligence",
      exam: "JEE-Advanced",
      cutoff: 419,
    },
    fees: 242000,
    placement: {
      average: 2148000,
      highest: 19800000,
    },
    userReviews: {
      rating: 4.3,
      totalReviews: 374,
      badge: "Best in Social Life",
    },
    nationalRank: 3,
    totalColleges: 275,
    rankingAgencies: ["The Week", "NIRF", "QS"],
  },
  {
    rank: 8,
    logo: "url/to/iitmadras-logo.png",
    name: "IIT Madras - Indian Institute of Technology",
    location: "Chennai, Tamil Nadu",
    approval: "AICTE Approved",
    course: {
      name: "B.Tech Artificial Intelligence",
      exam: "JEE-Advanced",
      cutoff: 419,
    },
    fees: 242000,
    placement: {
      average: 2148000,
      highest: 19800000,
    },
    userReviews: {
      rating: 4.3,
      totalReviews: 374,
      badge: "Best in Social Life",
    },
    nationalRank: 3,
    totalColleges: 275,
    rankingAgencies: ["The Week", "NIRF", "QS"],
  },
  {
    rank: 9,
    logo: "url/to/iitmadras-logo.png",
    name: "IIT Madras - Indian Institute of Technology",
    location: "Chennai, Tamil Nadu",
    approval: "AICTE Approved",
    course: {
      name: "B.Tech Artificial Intelligence",
      exam: "JEE-Advanced",
      cutoff: 419,
    },
    fees: 242000,
    placement: {
      average: 2148000,
      highest: 19800000,
    },
    userReviews: {
      rating: 4.3,
      totalReviews: 374,
      badge: "Best in Social Life",
    },
    nationalRank: 3,
    totalColleges: 275,
    rankingAgencies: ["The Week", "NIRF", "QS"],
  },
  {
    rank: 10,
    logo: "url/to/iitmadras-logo.png",
    name: "IIT Madras - Indian Institute of Technology",
    location: "Chennai, Tamil Nadu",
    approval: "AICTE Approved",
    course: {
      name: "B.Tech Artificial Intelligence",
      exam: "JEE-Advanced",
      cutoff: 419,
    },
    fees: 242000,
    placement: {
      average: 2148000,
      highest: 19800000,
    },
    userReviews: {
      rating: 4.3,
      totalReviews: 374,
      badge: "Best in Social Life",
    },
    nationalRank: 3,
    totalColleges: 275,
    rankingAgencies: ["The Week", "NIRF", "QS"],
  },
  {
    rank: 11,
    logo: "url/to/iitmadras-logo.png",
    name: "IIT Madras - Indian Institute of Technology",
    location: "Chennai, Tamil Nadu",
    approval: "AICTE Approved",
    course: {
      name: "B.Tech Artificial Intelligence",
      exam: "JEE-Advanced",
      cutoff: 419,
    },
    fees: 242000,
    placement: {
      average: 2148000,
      highest: 19800000,
    },
    userReviews: {
      rating: 4.3,
      totalReviews: 374,
      badge: "Best in Social Life",
    },
    nationalRank: 3,
    totalColleges: 275,
    rankingAgencies: ["The Week", "NIRF", "QS"],
  },
  {
    rank: 12,
    logo: "url/to/iitmadras-logo.png",
    name: "IIT Madras - Indian Institute of Technology",
    location: "Chennai, Tamil Nadu",
    approval: "AICTE Approved",
    course: {
      name: "B.Tech Artificial Intelligence",
      exam: "JEE-Advanced",
      cutoff: 419,
    },
    fees: 242000,
    placement: {
      average: 2148000,
      highest: 19800000,
    },
    userReviews: {
      rating: 4.3,
      totalReviews: 374,
      badge: "Best in Social Life",
    },
    nationalRank: 3,
    totalColleges: 275,
    rankingAgencies: ["The Week", "NIRF", "QS"],
  },
  {
    rank: 13,
    logo: "url/to/iitmadras-logo.png",
    name: "IIT Madras - Indian Institute of Technology",
    location: "Chennai, Tamil Nadu",
    approval: "AICTE Approved",
    course: {
      name: "B.Tech Artificial Intelligence",
      exam: "JEE-Advanced",
      cutoff: 419,
    },
    fees: 242000,
    placement: {
      average: 2148000,
      highest: 19800000,
    },
    userReviews: {
      rating: 4.3,
      totalReviews: 374,
      badge: "Best in Social Life",
    },
    nationalRank: 3,
    totalColleges: 275,
    rankingAgencies: ["The Week", "NIRF", "QS"],
  },
  {
    rank: 14,
    logo: "url/to/iitmadras-logo.png",
    name: "IIT Madras - Indian Institute of Technology",
    location: "Chennai, Tamil Nadu",
    approval: "AICTE Approved",
    course: {
      name: "B.Tech Artificial Intelligence",
      exam: "JEE-Advanced",
      cutoff: 419,
    },
    fees: 252000,
    placement: {
      average: 2148000,
      highest: 19800000,
    },
    userReviews: {
      rating: 4.3,
      totalReviews: 374,
      badge: "Best in Social Life",
    },
    nationalRank: 3,
    totalColleges: 275,
    rankingAgencies: ["The Week", "NIRF", "QS"],
  },
];

export default colleges;
