const colleges = [
  {
    rank: 1,
    logo: "url/to/iitmadras-logo.png",
    name: "IIT Madras - Indian Institute of Technology",
    location: "Chennai, Tamil Nadu",
    approval: "AICTE Approved",
    course: {
      name: "B.Tech Artificial Intelligence",
      exam: "JEE-Advanced",
      cutoff: 419,
    },
    fees: 243000,
    placement: {
      average: 2148000,
      highest: 19800000,
    },
    userReviews: {
      rating: 4.4,
      totalReviews: 374,
      badge: "Best in Social Life",
    },
    nationalRank: 1,
    totalColleges: 275,
    rankingAgencies: ["The Week", "NIRF", "QS"],
  },
  {
    rank: 2,
    logo: "url/to/iitmadras-logo.png",
    name: "IIT Madras - Indian Institute of Technology",
    location: "Chennai, Tamil Nadu",
    approval: "AICTE Approved",
    course: {
      name: "B.Tech Artificial Intelligence",
      exam: "JEE-Advanced",
      cutoff: 419,
    },
    fees: 342000,
    placement: {
      average: 2148000,
      highest: 19800000,
    },
    userReviews: {
      rating: 4.5,
      totalReviews: 374,
      badge: "Best in Social Life",
    },
    nationalRank: 2,
    totalColleges: 275,
    rankingAgencies: ["The Week", "NIRF", "QS"],
  },
  {
    rank: 3,
    logo: "url/to/iitmadras-logo.png",
    name: "IIT Madras - Indian Institute of Technology",
    location: "Chennai, Tamil Nadu",
    approval: "AICTE Approved",
    course: {
      name: "B.Tech Artificial Intelligence",
      exam: "JEE-Advanced",
      cutoff: 419,
    },
    fees: 292000,
    placement: {
      average: 2148000,
      highest: 19800000,
    },
    userReviews: {
      rating: 4.8,
      totalReviews: 374,
      badge: "Best in Social Life",
    },
    nationalRank: 4,
    totalColleges: 275,
    rankingAgencies: ["The Week", "NIRF", "QS"],
  },
  {
    rank: 4,
    logo: "url/to/iitmadras-logo.png",
    name: "IIT Madras - Indian Institute of Technology",
    location: "Chennai, Tamil Nadu",
    approval: "AICTE Approved",
    course: {
      name: "B.Tech Artificial Intelligence",
      exam: "JEE-Advanced",
      cutoff: 419,
    },
    fees: 742000,
    placement: {
      average: 2148000,
      highest: 19800000,
    },
    userReviews: {
      rating: 4.9,
      totalReviews: 374,
      badge: "Best in Social Life",
    },
    nationalRank: 5,
    totalColleges: 275,
    rankingAgencies: ["The Week", "NIRF", "QS"],
  },
  {
    rank: 5,
    logo: "url/to/iitmadras-logo.png",
    name: "IIT Madras - Indian Institute of Technology",
    location: "Chennai, Tamil Nadu",
    approval: "AICTE Approved",
    course: {
      name: "B.Tech Artificial Intelligence",
      exam: "JEE-Advanced",
      cutoff: 419,
    },
    fees: 242000,
    placement: {
      average: 2148000,
      highest: 19800000,
    },
    userReviews: {
      rating: 2.3,
      totalReviews: 374,
      badge: "Best in Social Life",
    },
    nationalRank: 3,
    totalColleges: 275,
    rankingAgencies: ["The Week", "NIRF", "QS"],
  },
  {
    rank: 6,
    logo: "url/to/iitmadras-logo.png",
    name: "IIT Madras - Indian Institute of Technology",
    location: "Chennai, Tamil Nadu",
    approval: "AICTE Approved",
    course: {
      name: "B.Tech Artificial Intelligence",
      exam: "JEE-Advanced",
      cutoff: 419,
    },
    fees: 252000,
    placement: {
      average: 2148000,
      highest: 19800000,
    },
    userReviews: {
      rating: 4.3,
      totalReviews: 374,
      badge: "Best in Social Life",
    },
    nationalRank: 9,
    totalColleges: 275,
    rankingAgencies: ["The Week", "NIRF", "QS"],
  },
  {
    rank: 7,
    logo: "url/to/iitmadras-logo.png",
    name: "IIT Madras - Indian Institute of Technology",
    location: "Chennai, Tamil Nadu",
    approval: "AICTE Approved",
    course: {
      name: "B.Tech Artificial Intelligence",
      exam: "JEE-Advanced",
      cutoff: 419,
    },
    fees: 452000,
    placement: {
      average: 2148000,
      highest: 19800000,
    },
    userReviews: {
      rating: 4.3,
      totalReviews: 374,
      badge: "Best in Social Life",
    },
    nationalRank: 7,
    totalColleges: 275,
    rankingAgencies: ["The Week", "NIRF", "QS"],
  },
  {
    rank: 8,
    logo: "url/to/iitmadras-logo.png",
    name: "IIT Madras - Indian Institute of Technology",
    location: "Chennai, Tamil Nadu",
    approval: "AICTE Approved",
    course: {
      name: "B.Tech Artificial Intelligence",
      exam: "JEE-Advanced",
      cutoff: 419,
    },
    fees: 542000,
    placement: {
      average: 2148000,
      highest: 19800000,
    },
    userReviews: {
      rating: 4,
      totalReviews: 374,
      badge: "Best in Social Life",
    },
    nationalRank: 11,
    totalColleges: 275,
    rankingAgencies: ["The Week", "NIRF", "QS"],
  },
  {
    rank: 9,
    logo: "url/to/iitmadras-logo.png",
    name: "IIT Madras - Indian Institute of Technology",
    location: "Chennai, Tamil Nadu",
    approval: "AICTE Approved",
    course: {
      name: "B.Tech Artificial Intelligence",
      exam: "JEE-Advanced",
      cutoff: 419,
    },
    fees: 512000,
    placement: {
      average: 2148000,
      highest: 19800000,
    },
    userReviews: {
      rating: 4.1,
      totalReviews: 374,
      badge: "Best in Social Life",
    },
    nationalRank: 10,
    totalColleges: 275,
    rankingAgencies: ["The Week", "NIRF", "QS"],
  },
  {
    rank: 10,
    logo: "url/to/iitmadras-logo.png",
    name: "IIT Madras - Indian Institute of Technology",
    location: "Chennai, Tamil Nadu",
    approval: "AICTE Approved",
    course: {
      name: "B.Tech Artificial Intelligence",
      exam: "JEE-Advanced",
      cutoff: 419,
    },
    fees: 352000,
    placement: {
      average: 2148000,
      highest: 19800000,
    },
    userReviews: {
      rating: 3.2,
      totalReviews: 374,
      badge: "Best in Social Life",
    },
    nationalRank: 13,
    totalColleges: 275,
    rankingAgencies: ["The Week", "NIRF", "QS"],
  },
  {
    rank: 11,
    logo: "url/to/iitmadras-logo.png",
    name: "IIT Madras - Indian Institute of Technology",
    location: "Chennai, Tamil Nadu",
    approval: "AICTE Approved",
    course: {
      name: "B.Tech Artificial Intelligence",
      exam: "JEE-Advanced",
      cutoff: 419,
    },
    fees: 652000,
    placement: {
      average: 2148000,
      highest: 19800000,
    },
    userReviews: {
      rating: 4.4,
      totalReviews: 374,
      badge: "Best in Social Life",
    },
    nationalRank: 153,
    totalColleges: 275,
    rankingAgencies: ["The Week", "NIRF", "QS"],
  },
  {
    rank: 12,
    logo: "url/to/iitmadras-logo.png",
    name: "IIT Madras - Indian Institute of Technology",
    location: "Chennai, Tamil Nadu",
    approval: "AICTE Approved",
    course: {
      name: "B.Tech Artificial Intelligence",
      exam: "JEE-Advanced",
      cutoff: 419,
    },
    fees: 240000,
    placement: {
      average: 2148000,
      highest: 19800000,
    },
    userReviews: {
      rating: 4.7,
      totalReviews: 374,
      badge: "Best in Social Life",
    },
    nationalRank: 6,
    totalColleges: 275,
    rankingAgencies: ["The Week", "NIRF", "QS"],
  },
  {
    rank: 13,
    logo: "url/to/iitmadras-logo.png",
    name: "IIT Madras - Indian Institute of Technology",
    location: "Chennai, Tamil Nadu",
    approval: "AICTE Approved",
    course: {
      name: "B.Tech Artificial Intelligence",
      exam: "JEE-Advanced",
      cutoff: 419,
    },
    fees: 292000,
    placement: {
      average: 2148000,
      highest: 19800000,
    },
    userReviews: {
      rating: 4.5,
      totalReviews: 374,
      badge: "Best in Social Life",
    },
    nationalRank: 18,
    totalColleges: 275,
    rankingAgencies: ["The Week", "NIRF", "QS"],
  },
  {
    rank: 14,
    logo: "url/to/iitmadras-logo.png",
    name: "IIT Madras - Indian Institute of Technology",
    location: "Chennai, Tamil Nadu",
    approval: "AICTE Approved",
    course: {
      name: "B.Tech Artificial Intelligence",
      exam: "JEE-Advanced",
      cutoff: 419,
    },
    fees: 852000,
    placement: {
      average: 2148000,
      highest: 19800000,
    },
    userReviews: {
      rating: 4.9,
      totalReviews: 374,
      badge: "Best in Social Life",
    },
    nationalRank: 19,
    totalColleges: 275,
    rankingAgencies: ["The Week", "NIRF", "QS"],
  },
];

export default colleges;
